version: '2'

volumes:
  orderer.bankx.org:
  peer0.bankx.org:
  peer1.bankx.org:
  portainer.bankx.org:

networks:
  bankx:

services:
  ca.bankx.org:
    extends:
      file: ../base/ca-base.yaml
      service: ca-base
    container_name: ca.bankx.org
    ports:
      - 8054:7054
    volumes:
      - ./fabric-ca/server:/etc/hyperledger/fabric-ca-server
    networks:
      - bankx

  zookeeper1.bankx.org:
    extends:
      file: ../base/orderer-base.yaml
      service: zookeeper-base
    container_name: zookeeper1.bankx.org
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1.bankx.org:2888:3888 server.2=zookeeper2.bankx.org:2888:3888 server.3=zookeeper3.bankx.org:2888:3888
    networks:
      - bankx

  zookeeper2.bankx.org:
    extends:
      file: ../base/orderer-base.yaml
      service: zookeeper-base
    container_name: zookeeper2.bankx.org
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1.bankx.org:2888:3888 server.2=zookeeper2.bankx.org:2888:3888 server.3=zookeeper3.bankx.org:2888:3888
    networks:
      - bankx

  zookeeper3.bankx.org:
    extends:
      file: ../base/orderer-base.yaml
      service: zookeeper-base
    container_name: zookeeper3.bankx.org
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1.bankx.org:2888:3888 server.2=zookeeper2.bankx.org:2888:3888 server.3=zookeeper3.bankx.org:2888:3888
    networks:
      - bankx

  kafka1.bankx.org:
    extends:
      file: ../base/orderer-base.yaml
      service: kafka-base
    container_name: kafka1.bankx.org
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.bankx.org:2181,zookeeper2.bankx.org:2181,zookeeper3.bankx.org:2181
    depends_on:
      - zookeeper1.bankx.org
      - zookeeper2.bankx.org
      - zookeeper3.bankx.org
    networks:
      - bankx
  
  kafka2.bankx.org:
    extends:
      file: ../base/orderer-base.yaml
      service: kafka-base
    container_name: kafka2.bankx.org
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.bankx.org:2181,zookeeper2.bankx.org:2181,zookeeper3.bankx.org:2181
    depends_on:
      - zookeeper1.bankx.org
      - zookeeper2.bankx.org
      - zookeeper3.bankx.org
    networks:
      - bankx

  kafka3.bankx.org:
    extends:
      file: ../base/orderer-base.yaml
      service: kafka-base
    container_name: kafka3.bankx.org
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.bankx.org:2181,zookeeper2.bankx.org:2181,zookeeper3.bankx.org:2181
    depends_on:
      - zookeeper1.bankx.org
      - zookeeper2.bankx.org
      - zookeeper3.bankx.org
    networks:
      - bankx

  kafka4.bankx.org:
    extends:
      file: ../base/orderer-base.yaml
      service: kafka-base
    container_name: kafka4.bankx.org
    environment:
      - KAFKA_BROKER_ID=4
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.bankx.org:2181,zookeeper2.bankx.org:2181,zookeeper3.bankx.org:2181
    depends_on:
      - zookeeper1.bankx.org
      - zookeeper2.bankx.org
      - zookeeper3.bankx.org
    networks:
      - bankx

  orderer.bankx.org:
    extends:
      file: ../base/orderer-base.yaml
      service: orderer-base
    container_name: orderer.bankx.org
    environment:
      - ORDERER_GENERAL_LOCALMSPID=bankxMSP
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/orderers/orderer.bankx.org/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/orderers/orderer.bankx.org/tls:/var/hyperledger/orderer/tls
      - orderer.bankx.org:/var/hyperledger/production
    ports:
      - 8050:7050
    depends_on: 
      - kafka1.bankx.org
      - kafka2.bankx.org
      - kafka3.bankx.org
      - kafka4.bankx.org
    networks:
      - bankx

  couchdb.peer0.bankx.org:
    extends:
      file: ../base/couchdb-base.yaml
      service: couchdb-base
    container_name: couchdb.peer0.bankx.org
    ports:
      - 8084:5984
    networks:
      - bankx

  peer0.bankx.org:
    extends:
      file: ../base/peer-base.yaml
      service: peer-base
    container_name: peer0.bankx.org
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bankx_bankx
      - CORE_PEER_ID=peer0.bankx.org
      - CORE_PEER_ADDRESS=peer0.bankx.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bankx.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bankx.org:7051
      - CORE_PEER_LOCALMSPID=bankxMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.bankx.org:5984
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peers/peer0.bankx.org/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peers/peer0.bankx.org/tls:/etc/hyperledger/fabric/tls
      - peer0.bankx.org:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - couchdb.peer0.bankx.org
    networks:
      - bankx

  couchdb.peer1.bankx.org:
    extends:
      file: ../base/couchdb-base.yaml
      service: couchdb-base
    container_name: couchdb.peer1.bankx.org
    ports:
      - 8184:5984
    networks:
      - bankx

  peer1.bankx.org:
    extends:
      file: ../base/peer-base.yaml
      service: peer-base
    container_name: peer1.bankx.org
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bankx_bankx
      - CORE_PEER_ID=peer1.bankx.org
      - CORE_PEER_ADDRESS=peer1.bankx.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.bankx.org:7051
      - CORE_PEER_LOCALMSPID=bankxMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.bankx.org:5984
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peers/peer1.bankx.org/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peers/peer1.bankx.org/tls:/etc/hyperledger/fabric/tls
      - peer1.bankx.org:/var/hyperledger/production
    ports:
      - 8151:7051
      - 8153:7053
    depends_on:
      - couchdb.peer1.bankx.org
    networks:
      - bankx

  cli.bankx.org:
    extends:
      file: ../base/cli-base.yaml
      service: cli-base
    container_name: cli.bankx.org
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    environment:
      - CORE_PEER_ID=cli.bankx.org
    depends_on:
      - orderer.bankx.org
      - peer0.bankx.org
      - peer1.bankx.org
    networks:
      - bankx

  portainer.bankx.org:
    extends:
      file: ../base/portainer-base.yaml
      service: portainer-base
    container_name: portainer.bankx.org
    ports:
      - 8000:9000
    volumes:
      - portainer.bankx.org:/data